# Generated by Django 4.2.1 on 2023-05-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('short_name', models.CharField(max_length=10)),
                ('asset_type', models.SmallIntegerField(choices=[(1, 'stock'), (2, 'bond'), (3, 'currency'), (4, 'commodity'), (5, 'cryptocurrency')], default=3, max_length=2)),
            ],
        ),
    ]
