# Generated by Django 4.2.1 on 2023-05-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_asset_asset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.SmallIntegerField(choices=[(1, 'stock'), (2, 'bond'), (3, 'currency'), (4, 'commodity'), (5, 'cryptocurrency')], default=5),
        ),
    ]
