# Generated by Django 4.2.1 on 2023-05-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cptracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='created',
            new_name='date_added',
        ),
    ]
