# Generated by Django 4.2.1 on 2023-05-30 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cptracker', '0002_rename_created_portfolio_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='balance',
        ),
        migrations.CreateModel(
            name='UserAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=12, max_digits=24)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cptracker.portfolio')),
            ],
        ),
    ]
