# Generated by Django 4.2.1 on 2023-05-30 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_asset_asset_type'),
        ('cptracker', '0004_userasset_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userasset',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.asset'),
        ),
    ]
